version: '3.1'

services:

  wordpress:
    image: wordpress:latest
    ports:
      - 9999:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./:/var/www/html/wp-content/plugins/blog-header-bar

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
